### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ahasall** [g-gomez/gulp-help-tasks-tree#1]
I tried this plugin but I've got this error. I think that it's related to lodash. Any idea ?

node_modules/gulp-help-tasks-tree/node_modules/lodash/index.js:4413
    function toObject(value) {
                     ^

RangeError: Maximum call stack size exceeded

**Comment by g-gomez** [comment]
Hello, do you have a loop into your dependencies ?

**Comment by mhh** [comment]
Hi,

I'm experiencing a similar problem with gulp-help-tasks-tree 1.0.1 and gulp 3.9.0 & 3.9.1. I've tried with node v0.10.41 and v4.4.3, both on Windows 7.  It can be reproduced using a gulpfile.js consisting of just the gulp-help-tasks-tree sample code:

``` javascript
var gulp = require('gulp');
var help = require('gulp-help-tasks-tree');

gulp.task('help', function() {
    gulp.src('gulpfile.js')
        .pipe(help({
            tasks: gulp.tasks,
            description: {
                'help': 'Display help and tasks tree'
            }
        }));
});
```

running `gulp help` produces:

```
[14:13:55] Using gulpfile ~\Projects\gulp-help-test\gulpfile.js
[14:13:55] Starting 'help'...
[14:13:55] Finished 'help' after 12 ms
gulp-help-test\node_modules\gulp-help-tasks-tree\node_modules\lodash\index.js:3065
      return function(object, iteratee, keysFunc) {
                     ^

RangeError: Maximum call stack size exceeded
    at gulp-help-test\node_modules\gulp-help-tasks-tree\node_modules\lodash\index.js:3065:22
    at baseForOwn (gulp-help-test\node_modules\gulp-help-tasks-tree\node_modules\lodash\index.js:2046:14)
    at gulp-help-test\node_modules\gulp-help-tasks-tree\node_modules\lodash\index.js:3043:18
    at Function.<anonymous> (gulp-help-test\node_modules\gulp-help-tasks-tree\node_modules\lodash\index.js:3346:13)
    at fillDependencies (gulp-help-test\node_modules\gulp-help-tasks-tree\index.js:43:11)
    at gulp-help-test\node_modules\gulp-help-tasks-tree\index.js:44:25
    at gulp-help-test\node_modules\gulp-help-tasks-tree\node_modules\lodash\index.js:3073:15
    at baseForOwn (gulp-help-test\node_modules\gulp-help-tasks-tree\node_modules\lodash\index.js:2046:14)
    at gulp-help-test\node_modules\gulp-help-tasks-tree\node_modules\lodash\index.js:3043:18
    at Function.<anonymous> (gulp-help-test\node_modules\gulp-help-tasks-tree\node_modules\lodash\index.js:3346:13)
```

**Comment by g-gomez** [comment]
Thank you for the example. I will correct it

**Comment by g-gomez** [comment]
I just realized it is my example for this plugin. I really need to add some unit tests ... 
If you want to use it while i'm fixing it, you can use it like this : 

```
var gulp = require('gulp');
var help = require('gulp-help-tasks-tree');

var description = {
    'help': 'Display help and tasks tree'
};

gulp.task('help', function () {
    gulp.src('gulpfile.js')
        .pipe(help({
            tasks: gulp.tasks,
            description: description
        }));
});
```

**Comment by falkolab** [comment]
```
/pathtomyapp/node_modules/lodash/index.js:4074
    function isArrayLike(value) {
                        ^

RangeError: Maximum call stack size exceeded
```
